# Generated by Django 3.2.3 on 2021-05-20 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rank',
        ),
    ]
