# Generated by Django 3.2.3 on 2021-05-21 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_reviewcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
