# Generated by Django 3.2.3 on 2021-05-24 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_review_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='nickname',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='username',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
