# Generated by Django 3.2.3 on 2021-05-20 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20210520_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_rank', to='movies.movie')),
            ],
        ),
    ]
