# Generated by Django 3.2.3 on 2021-05-25 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_movie_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='overview',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
