# Generated by Django 3.2.3 on 2021-05-20 18:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_alter_movierank_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True, null=True), blank=True, null=True, size=None),
        ),
    ]
